service: announcements

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: ${opt:region, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  runtime: python3.7
  timeout: 120
  environment:
    STAGE: ${opt:stage, 'dev'}
    ANNOUNCEMENTS_TABLE: !Ref AnnouncementsTable


  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:DescribeLogGroups
        - logs:FilterLogEvents
        - logs:DescribeLogStreams
        - logs:GetLogEvents
      Resource: "arn:aws:logs:${opt:region, self:provider.region}:*"
    - Effect: Allow
      Action:
        - ssm:GetParametersByPath
        - ssm:GetParameter
        - ssm:GetParameters
        - ssm:PutParameter
      Resource: "arn:aws:ssm:${opt:region, self:provider.region}:*"
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource: !GetAtt AnnouncementsTable.Arn


plugins:
  - serverless-wsgi
  - serverless-python-requirements
  - serverless-prune-plugin
  - serverless-dynamodb-local


functions:

  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY {proxy+}

resources:

  Resources:

    AnnouncementsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Announcements

        AttributeDefinitions:
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: timestamp
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1


    ErrorSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ErrorSNSTopic
        TopicName: ErrorSNSTopic


    DynamoDbThroughtputAlarm:
      Type: AWS::CloudWatch::Alarm
      DependsOn:
        - AnnouncementsTable
      Properties:
        ActionsEnabled: true
        AlarmActions:
          - !Ref ErrorSNSTopic
        AlarmDescription: For when the R/W of a dynamoDB table surpasses a certain throughput.
        ComparisonOperator: GreaterThanOrEqualToThreshold
        Dimensions:
          - Name: TableName
            Value: !Ref AnnouncementsTable
        EvaluationPeriods: 1
        MetricName: ConsumedWriteCapacityUnits
        Namespace: AWS/DynamoDB
        Period: 300
        Statistic: Average
        Threshold: 1


    AppOmegaErrorsMetricFilter:
      Type: AWS::Logs::MetricFilter
      Properties:
        LogGroupName: /aws/lambda/announcements-${opt:stage, self:provider.stage}-app
        FilterPattern: "ERROR"
        MetricTransformations:
          - MetricValue: "1"
            MetricNamespace: "API-${opt:stage, self:provider.stage}"
            MetricName: "ErrorsCount"


package:
  exclude:
    - .cache/**
    - coverage
    - .serverless/**
    - .dynamodb/**
    - node_modules/**
    - postman/**
    - sls
    - htmlcov/**
    - __pycache__/**
    - static/**
    - venv/**


custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: true
    usePipenv: true
  prune:
    automatic: true
    number: 3

  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
